name: "PR Triage"
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, locked]

permissions:
  pull-requests: write

jobs:
  assign-author:
    uses: vyos/.github/.github/workflows/assign-author.yml@feature/T6349-reusable-workflows
    secrets: inherit
