name: "PR Triage"
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, locked]

permissions:
  pull-requests: write

jobs:
  assign-author:
<<<<<<< HEAD
    uses: vyos/.github/.github/workflows/assign-author.yml@main
=======
    uses: vyos/.github/.github/workflows/assign-author.yml@feature/T6349-reusable-workflows
>>>>>>> 9a5897682a6d7fb59e2e90eb50b87dbbe8babaea
    secrets: inherit
