name: Check for unused imports using Pylint
on:
  pull_request_target:
    branches:
      - current
      - sagitta
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-unused-imports:
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@feature/T6349-reusable-workflows
    secrets: inherit
