name: Check for unused imports using Pylint
on:
  pull_request_target:
    branches:
      - current
      - sagitta

jobs:
  Check-Unused-Imports:
<<<<<<< HEAD
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@main
=======
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@feature/T6349-reusable-workflows
>>>>>>> 9a5897682a6d7fb59e2e90eb50b87dbbe8babaea
    secrets: inherit
