name: Check for unused imports using Pylint
on:
  pull_request_target:
    branches:
      - current
      - sagitta

jobs:
  Check-Unused-Imports:
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@main
    secrets: inherit
