name: Mergifyio backport

on: [issue_comment]

permissions:
    pull-requests: write

jobs:
  mergifyio-backport:
    uses: vyos/.github/.github/workflows/label-backport.yml@feature/T6349-reusable-workflows
    secrets: inherit
