---
name: J2 Lint

on:
  pull_request:
    branches:
      - current
      - crux
      - equuleus

jobs:
  j2lint:
<<<<<<< HEAD
    uses: vyos/.github/.github/workflows/lint-j2.yml@main
=======
    uses: vyos/.github/.github/workflows/lint-j2.yml@feature/T6349-reusable-workflows
>>>>>>> 9a5897682a6d7fb59e2e90eb50b87dbbe8babaea
    secrets: inherit
